### ISSUE TITLE
About MCG proposals on COCO

### ISSUE THREAD

**Issue by mingkeyzhang** [ppengtang/pcl.pytorch#10]
Hi, this code is very helpful to me. I want to test it on COCO. Could you share your MCG proposals? Thank you very much!

**Comment by ppengtang** [comment]
Hi, you can download MCG proposals on COCO [here](https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/mcg/#datasets) (choosing Boxes from MCG).

**Comment by mingkeyzhang** [comment]
Thank you very much!

**Comment by jieruyao49** [comment]
> Hi, this code is very helpful to me. I want to test it on COCO. Could you share your MCG proposals? Thank you very much!

Hi,I have download MCG boxes on COCO.How should I use it? Do I need to convert it into pkl file?
