### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: 'Outputs/vgg16_voc2007/'

### ISSUE THREAD

**Issue by ltc576935585** [ppengtang/pcl.pytorch#13]

**Comment by ppengtang** [comment]
Hi, I have not met this error before and thus don't know the reason for this. Could you provide more detailed information related to this error?

**Comment by ltc576935585** [comment]
When I use ''python tools/test_net.py --cfg configs/baselines/vgg16_voc2007.yaml \
    --load_ckpt Outputs/vgg16_voc2007/$MODEL_PATH \
    --dataset voc2007trainval''

I got this:
INFO test_net.py:  68: Called with args:
INFO test_net.py:  69: Namespace(cfg_file='configs/baselines/vgg16_voc2007.yaml', dataset='voc2007trainval', load_ckpt='Outputs/vgg16_voc2007/', load_detectron=None, multi_gpu_testing=False, output_dir=None, range=None, set_cfgs=[], vis=False)
INFO test_net.py:  80: Automatically set output directory to Outputs/test/
INFO test_net.py: 113: Testing with config:
INFO test_net.py: 114: {'BBOX_XFORM_CLIP': 4.8283137373023015,
 'CROP_RESIZE_WITH_MAX_POOL': True,
 'CUDA': False,
 'DATA_DIR': '/home/ltc/PycharmProjects/pcl.pytorch/data',
 'DATA_LOADER': {'NUM_THREADS': 4},
 'DEBUG': False,
 'DEDUP_BOXES': 0.125,
 'EPS': 1e-14,
 'EXPECTED_RESULTS': [],
 'EXPECTED_RESULTS_ATOL': 0.005,
 'EXPECTED_RESULTS_EMAIL': '',
 'EXPECTED_RESULTS_RTOL': 0.1,
 'FAST_RCNN': {'CONV_HEAD_DIM': 256,
               'MLP_HEAD_DIM': 4096,
               'NUM_STACKED_CONVS': 4,
               'ROI_BOX_HEAD': 'vgg16.roi_2mlp_head',
               'ROI_XFORM_METHOD': 'RoIPoolF',
               'ROI_XFORM_RESOLUTION': 7,
               'ROI_XFORM_SAMPLING_RATIO': 0},
 'MATLAB': 'matlab',
 'MODEL': {'CONV_BODY': 'vgg16.dilated_conv5_body',
           'LOAD_IMAGENET_PRETRAINED_WEIGHTS': True,
           'NUM_CLASSES': 20,
           'TYPE': 'generalized_rcnn'},
 'NUM_GPUS': 1,
 'OUTPUT_DIR': 'Outputs',
 'PIXEL_MEANS': array([[[102.9801, 115.9465, 122.7717]]]),
 'POOLING_MODE': 'crop',
 'POOLING_SIZE': 7,
 'PYTORCH_VERSION_LESS_THAN_040': False,
 'REFINE_TIMES': 3,
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/ltc/PycharmProjects/pcl.pytorch',
 'SOLVER': {'BASE_LR': 0.001,
            'BIAS_DOUBLE_LR': True,
            'BIAS_WEIGHT_DECAY': False,
            'GAMMA': 0.1,
            'LOG_LR_CHANGE_THRESHOLD': 1.1,
            'LRS': [],
            'LR_POLICY': 'steps_with_decay',
            'MAX_ITER': 1000,
            'MOMENTUM': 0.9,
            'SCALE_MOMENTUM': True,
            'SCALE_MOMENTUM_THRESHOLD': 1.1,
            'STEPS': [0, 35000],
            'STEP_SIZE': 30000,
            'TYPE': 'SGD',
            'WARM_UP_FACTOR': 0.3333333333333333,
            'WARM_UP_ITERS': 500,
            'WARM_UP_METHOD': 'linear',
            'WEIGHT_DECAY': 0.0005,
            'WEIGHT_DECAY_GN': 0.0},
 'TEST': {'BBOX_AUG': {'AREA_TH_HI': 32400,
                       'AREA_TH_LO': 2500,
                       'ASPECT_RATIOS': (),
                       'ASPECT_RATIO_H_FLIP': False,
                       'COORD_HEUR': 'ID',
                       'ENABLED': True,
                       'H_FLIP': True,
                       'MAX_SIZE': 4000,
                       'SCALES': (576, 688, 864),
                       'SCALE_H_FLIP': True,
                       'SCALE_SIZE_DEP': False,
                       'SCORE_HEUR': 'AVG'},
          'BBOX_VOTE': {'ENABLED': False,
                        'SCORING_METHOD': 'ID',
                        'SCORING_METHOD_BETA': 1.0,
                        'VOTE_TH': 0.8},
          'COMPETITION_MODE': True,
          'DATASETS': ('voc_2007_trainval',),
          'DETECTIONS_PER_IM': 100,
          'FORCE_JSON_DATASET_EVAL': False,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PRECOMPUTED_PROPOSALS': True,
          'PROPOSAL_FILES': ('data/selective_search_data',),
          'PROPOSAL_LIMIT': -1,
          'SCALE': 480,
          'SCORE_THRESH': 1e-05,
          'SOFT_NMS': {'ENABLED': False, 'METHOD': 'linear', 'SIGMA': 0.5}},
 'TRAIN': {'BATCH_SIZE_PER_IM': 4096,
           'BG_THRESH': 0.1,
           'CROWD_FILTER_THRESH': 0,
           'DATASETS': (),
           'FG_THRESH': 0.5,
           'FREEZE_CONV_BODY': False,
           'GRAPH_IOU_THRESHOLD': 0.4,
           'GT_MIN_AREA': -1,
           'IMS_PER_BATCH': 1,
           'MAX_PC_NUM': 5,
           'MAX_SIZE': 1000,
           'NUM_KMEANS_CLUSTER': 3,
           'PROPOSAL_FILES': ('data/selective_search_data/voc_2007_trainval.pkl',),
           'SCALES': (480, 576, 688, 864),
           'SNAPSHOT_ITERS': 10000,
           'USE_FLIPPED': True},
 'VGG': {'FREEZE_AT': 2,
         'IMAGENET_PRETRAINED_WEIGHTS': 'data/pretrained_model/vgg16_caffe.pth'},
 'VIS': False,
 'VIS_TH': 0.9}
loading annotations into memory...
Done (t=0.05s)
creating index...
index created!
loading annotations into memory...
Done (t=0.05s)
creating index...
index created!
INFO json_dataset.py: 219: Loading proposals from: data/selective_search_data/voc_2007_trainval.pkl
INFO json_dataset.py: 227:  1/5011
INFO json_dataset.py: 227:  2501/5011
INFO json_dataset.py: 227:  5001/5011
INFO test_engine.py: 314: loading checkpoint Outputs/vgg16_voc2007/
Traceback (most recent call last):
  File "tools/test_net.py", line 134, in <module>
    check_expected_results=True)
  File "/home/ltc/PycharmProjects/pcl.pytorch/lib/core/test_engine.py", line 127, in run_inference
    all_results = result_getter()
  File "/home/ltc/PycharmProjects/pcl.pytorch/lib/core/test_engine.py", line 107, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/ltc/PycharmProjects/pcl.pytorch/lib/core/test_engine.py", line 157, in test_net_on_dataset
    args, dataset_name, proposal_file, output_dir, gpu_id=gpu_id
  File "/home/ltc/PycharmProjects/pcl.pytorch/lib/core/test_engine.py", line 238, in test_net
    model = initialize_model_from_cfg(args, gpu_id=gpu_id)
  File "/home/ltc/PycharmProjects/pcl.pytorch/lib/core/test_engine.py", line 315, in initialize_model_from_cfg
    checkpoint = torch.load(load_name, map_location=lambda storage, loc: storage)
  File "/home/ltc/anaconda3/envs/MELM/lib/python3.6/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
IsADirectoryError: [Errno 21] Is a directory: 'Outputs/vgg16_voc2007/'



The source code you provided do not have`Output/vgg16_voc2007/', so I built one myself and it turned out that way.

**Comment by ltc576935585** [comment]
Sorry, I found out I made a silly mistake. I forgot to specify the model. Thanks for your replying.
