### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by ltc576935585** [ppengtang/pcl.pytorch#14]
I only have 8G memory. How can I modify the parameters? Batch-size is already 1. Please give me your guidance.Thank you.

**Comment by ppengtang** [comment]
Hi, you can try to use smaller training/testing scales by changing the parameter here: [1](https://github.com/ppengtang/pcl.pytorch/blob/master/configs/baselines/vgg16_voc2007.yaml#L21-L22), [2](https://github.com/ppengtang/pcl.pytorch/blob/master/configs/baselines/vgg16_voc2007.yaml#L27-L28), [3](https://github.com/ppengtang/pcl.pytorch/blob/master/configs/baselines/vgg16_voc2007.yaml#L34), [4](https://github.com/ppengtang/pcl.pytorch/blob/master/configs/baselines/vgg16_voc2012.yaml#L21-L22), [5](https://github.com/ppengtang/pcl.pytorch/blob/master/configs/baselines/vgg16_voc2012.yaml#L27-L28), and [6](https://github.com/ppengtang/pcl.pytorch/blob/master/configs/baselines/vgg16_voc2012.yaml#L34).

**Comment by ltc576935585** [comment]
I followed your guidance，changed (480, 576, 688, 864) #(480, 576, 688, 864, 1200)，(576, 688, 864) #(576, 688, 864, 1200)，and it can train Normaly.
