### ISSUE TITLE
Where can I get 'detection.pkl',I don't sure which on is the correct,please give me guidance.Thank you.

### ISSUE THREAD

**Issue by ltc576935585** [ppengtang/pcl.pytorch#15]
./tools/reeval.py $output_dir/detections.pkl \
    --dataset voc2007test --cfg configs/baselines/vgg16_voc2007.yaml

**Comment by ppengtang** [comment]
Hi, please make sure that you have run the command
`python tools/test_net.py --cfg configs/baselines/vgg16_voc2007.yaml \
  --load_ckpt Outputs/vgg16_voc2007/$model_path \
  --dataset voc2007test`
to generate 'detections.pkl'.
