### ISSUE TITLE
How can  I visualize the result?

### ISSUE THREAD

**Issue by ltc576935585** [ppengtang/pcl.pytorch#18]

**Comment by ppengtang** [comment]
You can follow the [faster-rcnn.pytorch](https://github.com/jwyang/faster-rcnn.pytorch) implementation to visualize results.

**Comment by hpu-dxx** [comment]
> _未提供说明。_
Have you successfully visualized the result?

**Comment by hpu-dxx** [comment]
> _No description provided._

@ltc576935585 Have you successfully visualized the result?
