### ISSUE TITLE
ConnectionRefusedError

### ISSUE THREAD

**Issue by zwyyy215** [ppengtang/pcl.pytorch#2]
mickey@a208-System-Product-Name:~/pcl.pytorch$ CUDA_VISIBLE_DEVICES=0 python tools/train_net_step.py --dataset voc2007   --cfg configs/baselines/vgg16_voc2007.yaml --bs 1 --nw 4 --iter_size 4

ConnectionRefusedError: [Errno 111] Connection refused

Hi,I don't know how to solve the problem.I Google the answer.I find when I change the nw to 0, and the error disappear.But there will be a new problem：
AttributeError: 'Variable' object has no attribute 'dtype'

**Comment by ppengtang** [comment]
Hi,

Thanks for your question.

I have tested the codes on my computer again. The codes do have a bug and I have updated the codes now. Please clone the current version code.

However, the bug I referred to before should not produce the bug you reported.
Please make sure that you have followed the [Installation](https://github.com/ppengtang/pcl.pytorch#installation) steps before running the codes.
Also, you should also check your system environment.

Hope these help you. I would really appreciate it if you could tell me whether you have fixed the bug or not.

**Comment by smcdonagh** [comment]
I receive similar error attempting to train with PyTorch 0.3.1.   Solved by upgrading to 0.4.1. 

Related info [here](https://github.com/lzx1413/PytorchSSD/issues/48)

**Comment by ppengtang** [comment]
Thanks. I have updated the software requirements in README.
Also, notice that we should use pyyaml 3.12 for multi-gpu testing.

**Comment by zwyyy215** [comment]
Thanks.I solved the problem by updating pytorch to 0.4.1.
