### ISSUE TITLE
VOC 2012 test

### ISSUE THREAD

**Issue by zhaohui-yang** [ppengtang/pcl.pytorch#24]
Hi, thanks for sharing this great repo! I noticed that you have the json file of voc_2012_test.json in your google drive. I wonder if it was released? As I remember, the results should be uploaded onto the server. So, I'm curious where can I get the annotations  for voc_2012_test. Thanks!

**Comment by zhaohui-yang** [comment]
By the way, this implementation could achieve mAP 0f 49.2, which outperforms mAP=43.5 in your PAMI paper, right?

**Comment by ppengtang** [comment]
Hi, the voc_2012_test.json only contains image information for the VOC 2012 test set, which is similar to the COCO test set. We need to upload results on the VOC 2012 test set to the server for evaluation.

For mAP, the mAPs and CorLocs obtained by this implementation are much higher than the results reported in our paper.

**Comment by zhaohui-yang** [comment]
Thanks, I know what you mean! :)
