### ISSUE TITLE
the role of `cal_minibatch_ratio`?

### ISSUE THREAD

**Issue by drcege** [ppengtang/pcl.pytorch#26]
I see you warpped a `MinibatchSampler` with in `BatchSampler`. It seems that you want to randomly permute the data. As documented, here `cal_minibatch_ratio` is for "_Given the ratio_list, we want to make the RATIO same for each minibatch on each GPU_"
https://github.com/ppengtang/pcl.pytorch/blob/d697e5f88b9232866a3a02554bba9fdfc6fa0d1a/lib/roi_data/loader.py#L78-L82

However, the problem is, if `cfg.TRAIN.IMS_PER_BATCH > 1`,  the ratios between `left_idx` and `right_idx` are unordered. The following code seems meaningless:
https://github.com/ppengtang/pcl.pytorch/blob/d697e5f88b9232866a3a02554bba9fdfc6fa0d1a/lib/roi_data/loader.py#L57-L65

**Comment by ppengtang** [comment]
Hi, for these codes, I just follow the implementations of Detectron.pytorch, and faster-rcnn.pytorch. Actually, in our experiments, we set cfg.TRAIN.IMS_PER_BATCH=1 and use step_size for larger mini-batch size.

**Comment by drcege** [comment]
Ok, I see. There's some redundant code.  
As long as cfg.TRAIN.IMS_PER_BATCH is guaranteed to be 1, there is no problem.
