### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by akshitac8** [ppengtang/pcl.pytorch#29]
Hi, I have been getting this problem when I am trying to run the baseline code on **COCO DATASET**. 
I think the main problem is this: ValueError: n_samples=2 should be >= n_clusters=3
It would be great if u could let me know how to solve it

**Comment by ppengtang** [comment]
Hi, you can try to filter out images with few proposals by modifying [these line of codes](https://github.com/ppengtang/pcl.pytorch/blob/master/lib/datasets/roidb.py#L99-L107).

**Comment by akshitac8** [comment]
Thanks, @ppengtang I have solved this issue :)
