### ISSUE TITLE
pcl loss in pytorch

### ISSUE THREAD

**Issue by zeyihuang** [ppengtang/pcl.pytorch#30]
Hi,
I was wondering if PCLLosses implemented in line 173 in pcl.py works or not? Does it achieve the same accuracy with the current CUDA one? If it works, does it cause slow training speed or larger memory cost? Thanks

**Comment by ppengtang** [comment]
Sorry, I don't remember the details of these codes... But I think these codes should not work or at least are much slower than the C/CUDA codes.
