### ISSUE TITLE
About Batch Size 

### ISSUE THREAD

**Issue by suyeH** [ppengtang/pcl.pytorch#31]
Hi, I read the code roughly and found that the training batch size of this pytorch implementation can only be 1. Because the number of selective search proposals of different image may be different and in lib/model/pcl/pcl.py, you assert batch size equal to 1.
`assert num_images == 1, 'batch size shoud be equal to 1'`
So, am I wrong or it's true that your code can only set batch size to 1?
Thanks.

**Comment by suyeH** [comment]
oh, I have figured out, sorry to bother.

**Comment by ppengtang** [comment]
Yes, we can only set `--bs` to `1` during training. But we set `--iter_size` to `4`, which means that the real batch size is `4` (because the real batch size equals to `bs * iter_size`).

**Comment by qpmnh** [comment]
Why would you use this strategy to set the real batch size ?
i.e., real batch size = bs * iter_size

**Comment by ppengtang** [comment]
> Why would you use this strategy to set the real batch size ?
> i.e., real batch size = bs * iter_size

@qpmnh There are two reasons.
1. Due to the GPU memory limitation, we cannot feed real batch size of images into a GPU at the same time.
2. We could feed images w/ different sizes in the same mini-batch.
