### ISSUE TITLE
Can not use workers. Exception in thread Thread-1.

### ISSUE THREAD

**Issue by NGUYEN96Fr** [ppengtang/pcl.pytorch#33]
Hi All,

I am struggling to set up a number of workers more than 0. It produced me errors as below  

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/nguyen/anaconda3/envs/pcl/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/nguyen/anaconda3/envs/pcl/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nguyen/anaconda3/envs/pcl/lib/python3.5/multiprocessing/resource_sharer.py", line 139, in _serve
    signal.pthread_sigmask(signal.SIG_BLOCK, range(1, signal.NSIG))
  File "/home/nguyen/anaconda3/envs/pcl/lib/python3.5/signal.py", line 60, in pthread_sigmask
    sigs_set = _signal.pthread_sigmask(how, mask)
ValueError: signal number 32 out of range`

No errors were generated during CUDA code compilation. I searched solutions for this error, it seems like it's a problem of python, it updated my python version to  3.7 by following some suggestions, but I am still stuck in it. 

**My configured environment:**

python = 3.5
cython = 0.28.5
pytorch = 0.4.1
cuda92
GNU Compiler Collection 70

 **My Nvidia toolkit version**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148

**Comment by ppengtang** [comment]
Hi, I have not met this issue before. It seems that this is a Python bug and you could try to upgrade your Python version: https://discuss.pytorch.org/t/valueerror-signal-number-32-out-of-range-when-loading-data-with-num-worker-0/39615/2. You can also try to run experiments using nvidia-docker.

**Comment by NGUYEN96Fr** [comment]
Hi, thanks for your help. After updating the python version to 3.6.10, I  could resolve the bug.
