### ISSUE TITLE
Runtime Error: Blob dimensions mismatch in the collate_minibatch function

### ISSUE THREAD

**Issue by NGUYEN96Fr** [ppengtang/pcl.pytorch#34]
Hi all,

I tried to run the codes with a configuration as following to load the VOC2007 dataset into the main thread:

`CUDA_VISIBLE_DEVICES=0 python tools/train_net_step.py --dataset voc2007 --cfg configs/baselines/vgg16_voc2007.yaml --bs 5 --nw 0 --iter_size 4`

 I got the error below : 

`
Traceback (most recent call last):
  File "tools/train_net_step.py", line 404, in main
    input_data = next(dataiterator)
  File "/home/nguyen/anaconda3/envs/pcl2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 322, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/nguyen/Documents/test-pcl.pytorch/pcl.pytorch/lib/roi_data/loader.py", line 154, in collate_minibatch
    minibatch = default_collate(mini_list)
  File "/home/nguyen/anaconda3/envs/pcl2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 189, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/nguyen/anaconda3/envs/pcl2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 189, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/nguyen/anaconda3/envs/pcl2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 178, in default_collate
    return torch.stack([torch.from_numpy(b) for b in batch], 0)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 900 and 320 in dimension 2 at /opt/conda/conda-bld/pytorch_1532579245307/work/aten/src/TH/generic/THTensorMath.cpp:3616
` 

The important notice is **RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 900 and 320 in dimension 2 ...**

What I understand is that blobs which form a mini list to feed into 'default_collate' need to have the same dimension, but when I checked that blob dimensions (batch_size = 5), what I got :

`
(3, 900, 1200)
(3, 320, 480)
(3, 381, 576)
(3, 648, 864)
(3, 799, 1200)
`

How can I fix this issue?

**Comment by ppengtang** [comment]
Hi, our current implementation does not support batch size larger than 1. So we must us `--bs 1`. Alternatively, we could use `--iter_size` for large batch size. The real batch size equals to `bs*iter_size`.

**Comment by NGUYEN96Fr** [comment]
Hi,
I am testing your models on some custom datasets. Could you share code by which you used to generate proposals for images?

**Comment by ppengtang** [comment]
> Hi,
> I am testing your models on some custom datasets. Could you share codes by which you used to generate proposals for images?

Hi, you could follow [these codes](https://github.com/rbgirshick/rcnn/tree/master/selective_search) to generate `.mat` format selective search proposals. I feel so sorry for that I cannot find the codes to convert `.mat` format selective search proposals to `.pkl` format selective search proposals. Maybe you could try to implement it by yourself.

**Comment by NGUYEN96Fr** [comment]
Hi, don't worry about that, I will do it by myself. Many thanks for your instruction.
