### ISSUE TITLE
How to use MCG boxes on COCO？

### ISSUE THREAD

**Issue by jieruyao49** [ppengtang/pcl.pytorch#35]
Hi,I have download MCG boxes on COCO.How should I use it? Do I need to convert it into pkl file?Could you share your pkl file on COCO?

**Comment by ppengtang** [comment]
Hi, I feel sorry for that I have not tried this PyTorch version codes on COCO, so I do not have .pkl format proposals for COCO. You could try to convert the original MCG boxes to .pkl format by yourself.

**Comment by jieruyao49** [comment]
> Hi, I feel sorry for that I have not tried this PyTorch version codes on COCO, so I do not have .pkl format proposals for COCO. You could try to convert the original MCG boxes to .pkl format by yourself.

thanks, i have converted the original MCG boxes to .pkl format by myself.

**Comment by ppengtang** [comment]
@jieruyao49 Hi, we found changing [this line of codes](https://github.com/ppengtang/pcl.pytorch/blob/master/lib/modeling/pcl_heads.py#L84) to `return 4.0 * loss.mean()` could obtain better results on COCO.

**Comment by jieruyao49** [comment]
Wow,I'll try to modify it.How did you find this way？

**Comment by ppengtang** [comment]
When I was training models on COCO, I found that the image classification branch is hard to converge. So I was wondering the reason is that, on PASCAL VOC, we compute image classification loss by - \sum (y_{i} log(p_{i}) + (1 - y_{i})(1 - log(p_{i})) / 20, whereas on COCO, we compute image classification loss by - \sum (y_{i} log(p_{i}) + (1 - y_{i})(1 - log(p_{i})) / 80.

**Comment by jieruyao49** [comment]
> When I was training models on COCO, I found that the image classification branch is hard to converge. So I was wondering the reason is that, on PASCAL VOC, we compute image classification loss by - \sum (y_{i} log(p_{i}) + (1 - y_{i})(1 - log(p_{i})) / 20, whereas on COCO, we compute image classification loss by - \sum (y_{i} log(p_{i}) + (1 - y_{i})(1 - log(p_{i})) / 80.

I also found this problem, but I did not find the corresponding solution, your answer inspired me.Thx!

**Comment by jieruyao49** [comment]
> When I was training models on COCO, I found that the image classification branch is hard to converge. So I was wondering the reason is that, on PASCAL VOC, we compute image classification loss by - \sum (y_{i} log(p_{i}) + (1 - y_{i})(1 - log(p_{i})) / 20, whereas on COCO, we compute image classification loss by - \sum (y_{i} log(p_{i}) + (1 - y_{i})(1 - log(p_{i})) / 80.

When I was training coco, there was a error,as shown below,how should i do?
`Traceback (most recent call last):
  File "train_net_step.py", line 445, in <module>
    main()
  File "train_net_step.py", line 415, in main
    net_outputs = pcl(**input_data)
  File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/nn/parallel/data_parallel.py", line 108, in forward
    outputs = [self.module(*inputs[0], **kwargs[0])]
  File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/modeling/model_builder.py", line 105, in forward
    return self._forward(data, rois, labels)
  File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/modeling/model_builder.py", line 141, in _forward
    pcl_output = PCL(boxes, mil_score, im_labels, refine)
  File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/model/pcl/pcl.py", line 32, in PCL
    im_labels.copy())
  File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/model/pcl/pcl.py", line 81, in _get_graph_centers
    idxs_tmp = _get_top_ranking_propoals(cls_prob_tmp[idxs].reshape(-1, 1))
  File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/model/pcl/pcl.py", line 50, in _get_top_ranking_propoals
    random_state=cfg.RNG_SEED).fit(probs)
  File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/sklearn/cluster/_kmeans.py", line 998, in fit
    _num_samples(X), self.n_clusters))
ValueError: n_samples=2 should be >= n_clusters=3
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f1dc3cede48>>
Traceback (most recent call last):
  File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
    self._shutdown_workers()
  File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
`

**Comment by ppengtang** [comment]
> > When I was training models on COCO, I found that the image classification branch is hard to converge. So I was wondering the reason is that, on PASCAL VOC, we compute image classification loss by - \sum (y_{i} log(p_{i}) + (1 - y_{i})(1 - log(p_{i})) / 20, whereas on COCO, we compute image classification loss by - \sum (y_{i} log(p_{i}) + (1 - y_{i})(1 - log(p_{i})) / 80.
> 
> When I was training coco, there was a error,as shown below,how should i do?
> 
> `Traceback (most recent call last): File "train_net_step.py", line 445, in <module> main() File "train_net_step.py", line 415, in main net_outputs = pcl(**input_data) File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__ result = self.forward(*input, **kwargs) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/nn/parallel/data_parallel.py", line 108, in forward outputs = [self.module(*inputs[0], **kwargs[0])] File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__ result = self.forward(*input, **kwargs) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/modeling/model_builder.py", line 105, in forward return self._forward(data, rois, labels) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/modeling/model_builder.py", line 141, in _forward pcl_output = PCL(boxes, mil_score, im_labels, refine) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/model/pcl/pcl.py", line 32, in PCL im_labels.copy()) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/model/pcl/pcl.py", line 81, in _get_graph_centers idxs_tmp = _get_top_ranking_propoals(cls_prob_tmp[idxs].reshape(-1, 1)) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/model/pcl/pcl.py", line 50, in _get_top_ranking_propoals random_state=cfg.RNG_SEED).fit(probs) File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/sklearn/cluster/_kmeans.py", line 998, in fit _num_samples(X), self.n_clusters)) ValueError: n_samples=2 should be >= n_clusters=3 Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f1dc3cede48>> Traceback (most recent call last): File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 349, in __del__ self._shutdown_workers() File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers self.worker_result_queue.get() File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/queues.py", line 337, in get return _ForkingPickler.loads(res) File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd fd = df.detach() File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach with _resource_sharer.get_connection(self._id) as conn: File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection c = Client(address, authkey=process.current_process().authkey) File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/connection.py", line 487, in Client c = SocketClient(address) File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient s.connect(address) ConnectionRefusedError: [Errno 111] Connection refused `

@jieruyao49 You could filter images with small # proposal boxes (e.g., < 100) by revising [this line of codes](https://github.com/ppengtang/pcl.pytorch/blob/b78e1ef8f16fc71fa0e4b62b79bb44cb6e4f4bdb/lib/datasets/roidb.py#L105).

**Comment by jieruyao49** [comment]
> > > When I was training models on COCO, I found that the image classification branch is hard to converge. So I was wondering the reason is that, on PASCAL VOC, we compute image classification loss by - \sum (y_{i} log(p_{i}) + (1 - y_{i})(1 - log(p_{i})) / 20, whereas on COCO, we compute image classification loss by - \sum (y_{i} log(p_{i}) + (1 - y_{i})(1 - log(p_{i})) / 80.
> > 
> > 
> > When I was training coco, there was a error,as shown below,how should i do?
> > `Traceback (most recent call last): File "train_net_step.py", line 445, in <module> main() File "train_net_step.py", line 415, in main net_outputs = pcl(**input_data) File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__ result = self.forward(*input, **kwargs) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/nn/parallel/data_parallel.py", line 108, in forward outputs = [self.module(*inputs[0], **kwargs[0])] File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__ result = self.forward(*input, **kwargs) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/modeling/model_builder.py", line 105, in forward return self._forward(data, rois, labels) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/modeling/model_builder.py", line 141, in _forward pcl_output = PCL(boxes, mil_score, im_labels, refine) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/model/pcl/pcl.py", line 32, in PCL im_labels.copy()) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/model/pcl/pcl.py", line 81, in _get_graph_centers idxs_tmp = _get_top_ranking_propoals(cls_prob_tmp[idxs].reshape(-1, 1)) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/model/pcl/pcl.py", line 50, in _get_top_ranking_propoals random_state=cfg.RNG_SEED).fit(probs) File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/sklearn/cluster/_kmeans.py", line 998, in fit _num_samples(X), self.n_clusters)) ValueError: n_samples=2 should be >= n_clusters=3 Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f1dc3cede48>> Traceback (most recent call last): File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 349, in __del__ self._shutdown_workers() File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers self.worker_result_queue.get() File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/queues.py", line 337, in get return _ForkingPickler.loads(res) File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd fd = df.detach() File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach with _resource_sharer.get_connection(self._id) as conn: File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection c = Client(address, authkey=process.current_process().authkey) File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/connection.py", line 487, in Client c = SocketClient(address) File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient s.connect(address) ConnectionRefusedError: [Errno 111] Connection refused `
> 
> @jieruyao49 You could filter images with small # proposal boxes (e.g., < 100) by revising [this line of codes](https://github.com/ppengtang/pcl.pytorch/blob/b78e1ef8f16fc71fa0e4b62b79bb44cb6e4f4bdb/lib/datasets/roidb.py#L105).

when i  filted images with small proposal boxes,It accelerates the generation of errors. 
About the error that "n_samples=2 should be >= n_clusters=3",this is because in the code(in json_dataset.py & minibatch.py) has been filtered proposal many times, and the number of proposal that enter the training is less than five.So I only selected the filtered data with more than ten boxes for training.About the error that "Connection refused ",when I set nw = 0, the error doesn't exist.
However,when I test it,the results showed that mAP=0.What is the possibility of this results?

**Comment by ppengtang** [comment]
> > > > When I was training models on COCO, I found that the image classification branch is hard to converge. So I was wondering the reason is that, on PASCAL VOC, we compute image classification loss by - \sum (y_{i} log(p_{i}) + (1 - y_{i})(1 - log(p_{i})) / 20, whereas on COCO, we compute image classification loss by - \sum (y_{i} log(p_{i}) + (1 - y_{i})(1 - log(p_{i})) / 80.
> > > 
> > > 
> > > When I was training coco, there was a error,as shown below,how should i do?
> > > `Traceback (most recent call last): File "train_net_step.py", line 445, in <module> main() File "train_net_step.py", line 415, in main net_outputs = pcl(**input_data) File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__ result = self.forward(*input, **kwargs) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/nn/parallel/data_parallel.py", line 108, in forward outputs = [self.module(*inputs[0], **kwargs[0])] File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__ result = self.forward(*input, **kwargs) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/modeling/model_builder.py", line 105, in forward return self._forward(data, rois, labels) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/modeling/model_builder.py", line 141, in _forward pcl_output = PCL(boxes, mil_score, im_labels, refine) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/model/pcl/pcl.py", line 32, in PCL im_labels.copy()) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/model/pcl/pcl.py", line 81, in _get_graph_centers idxs_tmp = _get_top_ranking_propoals(cls_prob_tmp[idxs].reshape(-1, 1)) File "/home/rubyyao/PycharmProjects/pcl_pytorch/lib/model/pcl/pcl.py", line 50, in _get_top_ranking_propoals random_state=cfg.RNG_SEED).fit(probs) File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/sklearn/cluster/_kmeans.py", line 998, in fit _num_samples(X), self.n_clusters)) ValueError: n_samples=2 should be >= n_clusters=3 Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f1dc3cede48>> Traceback (most recent call last): File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 349, in __del__ self._shutdown_workers() File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 328, in _shutdown_workers self.worker_result_queue.get() File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/queues.py", line 337, in get return _ForkingPickler.loads(res) File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd fd = df.detach() File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach with _resource_sharer.get_connection(self._id) as conn: File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection c = Client(address, authkey=process.current_process().authkey) File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/connection.py", line 487, in Client c = SocketClient(address) File "/home/rubyyao/anaconda3/envs/pcl_pytorch/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient s.connect(address) ConnectionRefusedError: [Errno 111] Connection refused `
> > 
> > 
> > @jieruyao49 You could filter images with small # proposal boxes (e.g., < 100) by revising [this line of codes](https://github.com/ppengtang/pcl.pytorch/blob/b78e1ef8f16fc71fa0e4b62b79bb44cb6e4f4bdb/lib/datasets/roidb.py#L105).
> 
> @ppengtang when i filted images with small proposal boxes,It accelerates the generation of errors.
> About the error that "n_samples=2 should be >= n_clusters=3",this is because in the code(in json_dataset.py & minibatch.py) has been filtered proposal many times, and the number of proposal that enter the training is less than five.So I only selected the filtered data with more than ten boxes for training.About the error that "Connection refused ",when I set nw = 0, the error doesn't exist.
> When I test the code, map = 15.8. Do you test the code? Can the results reach the results mentioned in the paper?

@jieruyao49 My college obtains mAP@0.5 > 18.0 after training 30K iterations on COCO (using `return 4.0 * loss.mean()`). So I think after training more iterations, we could get higher mAP which matches the results reported in our paper.

**Comment by HMCCMH** [comment]
> 

Could you meet the problem that the program for testing the coco dataset was killed at last.
