### ISSUE TITLE
About image scales

### ISSUE THREAD

**Issue by 842430478** [ppengtang/pcl.pytorch#4]
Hi, I find the code resize the image to some scales. However, the "resize" is not based on the shortest side. For example, I find some images are resized to (432, 576) or (575, 864). The longest side is resized to the scales. Could you tell me why?

**Comment by ppengtang** [comment]
Yes, in this version codes I set the longest side to the scales. Because I found that this setting doesn't influence performance and requires less gpu memories.

**Comment by 842430478** [comment]
Tks!
