### ISSUE TITLE
Selective Search Proposals Documents 

### ISSUE THREAD

**Issue by dingjietao** [ppengtang/pcl.pytorch#40]
Thanks for your outstanding work first!
I want to apply the PCL model to my own datasets, but I meet some obstructs. In your model , you used  Selective Search Proposals data "voc_2007_trainval.pkl" and "voc_2007_test.pkl". But I don't know how to get the two documents about my own datasets. Could you give me some tips? I would appreciate it if you could help me！

**Comment by ppengtang** [comment]
Hi, sorry for the delayed reply, I was busy these days. You could check [these codes](https://github.com/rbgirshick/rcnn/tree/master/selective_search) to generate matlab format selective search proposals first. Then you could check the format of "voc_2007_trainval.pkl" / "voc_2007_test.pkl" and then convert the matlab format proposals into python format proposals.
