### ISSUE TITLE
Are there any plans for an updated Pytorch version?

### ISSUE THREAD

**Issue by anonymousiccv** [ppengtang/pcl.pytorch#42]
Hi Tang,
Are there any plans for an updated Pytorch version > 1.0?
Thanks!

**Comment by ppengtang** [comment]
Hi, I have an internal version which supports PyTorch 1.6. I will update the codes soon.

**Comment by anonymousiccv** [comment]
Thanks very much！
Can't wait to see.

**Comment by ppengtang** [comment]
Hi @anonymousiccv , please check the master branch for updated codes.
