### ISSUE TITLE
About PCLLosses

### ISSUE THREAD

**Issue by jiujiangluck** [ppengtang/pcl.pytorch#43]
About PCLLosses  `line 198`
https://github.com/ppengtang/pcl.pytorch/blob/b78e1ef8f16fc71fa0e4b62b79bb44cb6e4f4bdb/lib/model/pcl/pcl.py#L190-L199

The condition should be `pc_labels[0, i] == c`

I have found the c version.

https://github.com/ppengtang/pcl.pytorch/blob/b78e1ef8f16fc71fa0e4b62b79bb44cb6e4f4bdb/lib/model/pcl_losses/src/pcl_losses_kernel.cu#L24-L49

**Comment by ppengtang** [comment]
Hi, sorry for the delayed reply. The shapes of `pc_labels` in Python codes and C/CUDA codes are different.
