### ISSUE TITLE
About OICR and PCL

### ISSUE THREAD

**Issue by husuqi** [ppengtang/pcl.pytorch#44]
In  /lib/modeling/model_builder.py ,lines 91 and 145-150,useOICRLosses() and OICR()  ,does this represent the use of OICR rather than PCL optimization methods.Thanks

**Comment by ppengtang** [comment]
Yes. As stated in [Updates](https://github.com/ppengtang/pcl.pytorch#updates), we change to OICR.

**Comment by husuqi** [comment]
Okay,Thanks

**Comment by vadimkantorov** [comment]
Hi @ppengtang!

Could you please expand on motivations of switching from PCL to OICR? I assume it achieves better accuracy, but would you offer any comments / thoughts why would that be?

Thanks!
