### ISSUE TITLE
map metric

### ISSUE THREAD

**Issue by DeidaraYang** [ppengtang/pcl.pytorch#47]
Hi author, I just wanna to know about the metric you used on VOC 2007 and 2012 respectively.

**Comment by ppengtang** [comment]
The metrics include the standard object detection metric mAP on test sets and CorLoc on trainval sets.

**Comment by DeidaraYang** [comment]
thanks for replying. I mean I wanna to know you used 07metirc on VOC07 and 10metirc on VOC12?

**Comment by ppengtang** [comment]
We use 07metric for VOC07, see [this line of codes](https://github.com/ppengtang/pcl.pytorch/blob/master/lib/datasets/voc_dataset_evaluator.py#L152). For VOC12, since we don't have test set gts for mAP evaluation, we submit the results to the VOC 2012 evaluation website to get mAP numbers.

**Comment by DeidaraYang** [comment]
Thanks author!
