### ISSUE TITLE
Bounding boxes in COCO style JSON

### ISSUE THREAD

**Issue by George-Holbrow-Wilshaw** [ppengtang/pcl.pytorch#49]
In the function _add_gt_annotations in json_dataset.py the code implies that bounding boxes are needed in the COCO style JSON annotations file (i.e. obj['bbox']). 

I am trying to train this model on my own data, but since the purpose is weakly supervised learning, I have image level labels, but no bounding boxes other than those generated in selective search. How do I proceed, or am I completely missing the point here? 

Many thanks in advance.

**Comment by ppengtang** [comment]
Hi, `_add_gt_annotations` is to get image-level labels from bbox-level labels available for COCO / VOC. There are two options to get image-level labels as follows.
1. Convert your annotations to the COCO format and use some random numbers for box coordinates (like `1, 1, 2, 2`) and image label as box labels. If an image corresponds to multiple classes, generate a box for each class (for example, if an image contains both person and car, generate a box with coordinate `1, 1, 2, 2` and label `person` and another box with coordinate `1, 1, 2, 2` and label `car`.
2. Re-write `_add_gt_annotations` to load image-level labels only.

**Comment by George-Holbrow-Wilshaw** [comment]
This is incredibly helpful, thank you very much.
