### ISSUE TITLE
Can't download the models trained on PASCAL VOC

### ISSUE THREAD

**Issue by Yuting-Qiang** [ppengtang/pcl.pytorch#5]
The link leaved there is an empty directory, could you please upload the trained model? Thank you !

**Comment by ppengtang** [comment]
Hi, I feel so sorry for the delayed reply because I'm too busy this week.

I have tried to upload the model to the Google drive, but due to the Internet problem, I cannot complete the uploading. Next week I'll try to upload the model again or upload it to another place such as Baidu Yun.

**Comment by ppengtang** [comment]
Hi,
The model trained on PASCAL VOC 2007 is available on [Baidu Yun](https://pan.baidu.com/s/1BK1STmTOcLypyz1HPIhf_Q) (please use code bch4).
