### ISSUE TITLE
The implementation of imagenet train1k sampling

### ISSUE THREAD

**Issue by 1170300714** [ppengtang/pcl.pytorch#50]
> Hi @ppengtang, sorry to bother you again.
> I try to sample images from training set use the train_pos__.txt in `ILSVRC2013_devkit/data/det_lists`. But ~131K images could be obtained. Did you also sampled any negative images from ILSVRC2013_DET_train_extra using train_neg__.txt.

Thank for your great work!
I also meet the sample problem as him. I load the train_pos_1.txt to train_pos_201.txt and sample max 1000 line from each file, concate them to get the 'train1k' set. But the number of it is only ~131k, which is not the same as your paper report. 
So could you release the code or give me a brief description of the sampling algorithm？Thanks a lot!!

**Comment by ppengtang** [comment]
Sorry I don't remember the details and cannot find the codes. I think I just randomly sample 1000 files for each class. ~131k images should work, see #21 
To generate proposals, I use EdgeBoxes to generate at most 2048 proposals for each image.

**Comment by 1170300714** [comment]
> Sorry I don't remember the details and cannot find the codes. I think I just randomly sample 1000 files for each class. ~131k images should work, see #21
> To generate proposals, I use EdgeBoxes to generate at most 2048 proposals for each image.

Thanks a lot！
