### ISSUE TITLE
About result of vgg16_voc2007.xml

### ISSUE THREAD

**Issue by Name4H** [ppengtang/pcl.pytorch#51]
The  result of vgg16_voc2007.xml with WITH_FRCNN:Fasle   map is 50.06.and   WITH_FRCNN:True map is 51..50,Is this normal？

**Comment by ppengtang** [comment]
Hi, sorry I don't remember the numbers of WITH_FRCNN: False. For WITH_FRCNN: True, mAP 51.50 should be reasonable. You could try different random seeds (1~10) to reproduce the reported number.

**Comment by Name4H** [comment]
thanks，I will try

**Comment by hhhh12345678** [comment]
Hi, I am getting troubles with the result of vgg16_voc2007.

I used the default hyper-parameters to train the net, but got only 45.48mAP with WITH_FRCNN on.

I have read relate issues about performance dropping, but I found the results I got seems much lower.

my environment as below:

cuda 10.1 + pytorch 1.5.1 + RTX2080Ti
