### ISSUE TITLE
about network structure question

### ISSUE THREAD

**Issue by dingjietao** [ppengtang/pcl.pytorch#53]
I read your improved code， about the 3rd improvement point （add bounding box regression），what I understand is after n refinements added  bounding box regression，not after each refinement added  bounding box regression. And I want to know what I understand is right or not.

**Comment by ppengtang** [comment]
Yes. We follow [this paper](https://arxiv.org/pdf/1911.12148.pdf) to add bounding box regression after the third refinement branch.

**Comment by dingjietao** [comment]
> Yes. We follow [this paper](https://arxiv.org/pdf/1911.12148.pdf) to add bounding box regression after the third refinement branch.

thanks
