### ISSUE TITLE
The problem about the pkl of selective_search 

### ISSUE THREAD

**Issue by HMCCMH** [ppengtang/pcl.pytorch#56]
I want to use my own data to train the model but the first problem is coming that how to use selective search to generate **.pkl**
I first found the [website](https://github.com/WalterMa/SelectiveSearch-RCNN). I use the **demo.m** to generate the **.mat**. 
How can I transform the **.mat** to **.pkl**? I don't  the mean of the outcoming printed by **voc_2007_trainval.pkl**  such like array[1,1,1,1,1,....,1,1,1],dtype=float32. And the encoding of the **.pkl** is also unknown. 
So if you train the model on your own data? Or do you knoww how to generate **voc_2007_trainval.pkl**? I want to generate  selective search proposals pkl on my own data by reference. Thank you very much!

**Comment by ppengtang** [comment]
Hi, you could check these codes: https://github.com/ppengtang/pcl.pytorch/blob/76656a6586759524ed6f3bcf8efbf47e6150311d/lib/datasets/json_dataset.py#L215
The .pkl files contain Python Dictionaries.
