### ISSUE TITLE
About mAP results of vgg16_voc2007_more.yaml

### ISSUE THREAD

**Issue by PURE-melo** [ppengtang/pcl.pytorch#57]
Thanks for your nice code. I found the result of vgg16_voc2007_more.yaml is only  51.7~52.1 mAP in my experiment. Can you release your 54.1mAP model weights?

**Comment by soongyuu** [comment]
Hello, I am also debugging this experiment using vgg_voc2007_more.yaml, but I have encountered some problems.
In config, how to set some parameters?
Such as _C. MODEL. CONV_BODY = ' '
Your reply will be highly appreciated

**Comment by soongyuu** [comment]
> Thanks for your nice code. I found the result of vgg16_voc2007_more.yaml is only 51.7~52.1 mAP in my experiment. Can you release your 54.1mAP model weights?

Hello, I am also debugging this experiment using vgg_voc2007_more.yaml, but I have encountered some problems.
In config, how to set some parameters?
Such as _C. MODEL. CONV_BODY = ' '
Your reply will be highly appreciated

**Comment by soongyuu** [comment]
> Thanks for your nice code. I found the result of vgg16_voc2007_more.yaml is only 51.7~52.1 mAP in my experiment. Can you release your 54.1mAP model weights?

Hi, I'm duplicating this code as well.But there are some problems, could you please tell me?For example, CUDA error out of memory was encountered in the training，while the video memory is sufficient.Your reply will be greatly appreciated

**Comment by PURE-melo** [comment]
> > Thanks for your nice code. I found the result of vgg16_voc2007_more.yaml is only 51.7~52.1 mAP in my experiment. Can you release your 54.1mAP model weights?
> 
> Hi, I'm duplicating this code as well.But there are some problems, could you please tell me?For example, CUDA error out of memory was encountered in the training，while the video memory is sufficient.Your reply will be greatly appreciated

Sorry, I just followed the process in author's readme.txt. In my experiment, 1080ti's GPU memory is sufficient. So, I don’t know why your GPU memory overflows.

**Comment by soongyuu** [comment]
> > > Thanks for your nice code. I found the result of vgg16_voc2007_more.yaml is only 51.7~52.1 mAP in my experiment. Can you release your 54.1mAP model weights?
> > 
> > 
> > Hi, I'm duplicating this code as well.But there are some problems, could you please tell me?For example, CUDA error out of memory was encountered in the training，while the video memory is sufficient.Your reply will be greatly appreciated
> 
> Sorry, I just followed the process in author's readme.txt. In my experiment, 1080ti's GPU memory is sufficient. So, I don’t know why your GPU memory overflows.

Thank you very much for your reply. My GPU is also 1080T.
Pytorch = = 1.8.0 torchvision = = 0.9.0 cuda 11.0 MMCV  = = 1.3.5.
May I have your email address?
To facilitate future communication.
I am also in a university in Xi 'an.
It's a pleasure to meet you.
My email address is songyu888@yeah.net

**Comment by PURE-melo** [comment]
> > > > Thanks for your nice code. I found the result of vgg16_voc2007_more.yaml is only 51.7~52.1 mAP in my experiment. Can you release your 54.1mAP model weights?
> > > 
> > > 
> > > Hi, I'm duplicating this code as well.But there are some problems, could you please tell me?For example, CUDA error out of memory was encountered in the training，while the video memory is sufficient.Your reply will be greatly appreciated
> > 
> > 
> > Sorry, I just followed the process in author's readme.txt. In my experiment, 1080ti's GPU memory is sufficient. So, I don’t know why your GPU memory overflows.
> 
> Thank you very much for your reply. My GPU is also 1080T.
> Pytorch = = 1.8.0 torchvision = = 0.9.0 cuda 11.0 MMCV = = 1.3.5.
> May I have your email address?
> To facilitate future communication.
> I am also in a university in Xi 'an.
> It's a pleasure to meet you.
> My email address is [songyu888@yeah.net](mailto:songyu888@yeah.net)

Ok, I've sent you my email. It's my pleasure to meet you too.

**Comment by ppengtang** [comment]
> Thanks for your nice code. I found the result of vgg16_voc2007_more.yaml is only 51.7~52.1 mAP in my experiment. Can you release your 54.1mAP model weights?

Sorry for the late reply. The models are available [here](https://drive.google.com/drive/folders/1OG56zqBv_gbLsDXySpLi55bYy5Q9Tf2-?usp=sharing).

**Comment by ppengtang** [comment]
> > > > Thanks for your nice code. I found the result of vgg16_voc2007_more.yaml is only 51.7~52.1 mAP in my experiment. Can you release your 54.1mAP model weights?
> > > 
> > > 
> > > Hi, I'm duplicating this code as well.But there are some problems, could you please tell me?For example, CUDA error out of memory was encountered in the training，while the video memory is sufficient.Your reply will be greatly appreciated
> > 
> > 
> > Sorry, I just followed the process in author's readme.txt. In my experiment, 1080ti's GPU memory is sufficient. So, I don’t know why your GPU memory overflows.
> 
> Thank you very much for your reply. My GPU is also 1080T.
> Pytorch = = 1.8.0 torchvision = = 0.9.0 cuda 11.0 MMCV = = 1.3.5.
> May I have your email address?
> To facilitate future communication.
> I am also in a university in Xi 'an.
> It's a pleasure to meet you.
> My email address is [songyu888@yeah.net](mailto:songyu888@yeah.net)

Have you fixed this issue? Maybe you could follow my [settings](https://github.com/ppengtang/pcl.pytorch/blob/master/install.sh) to use pytorch 1.6.0 and torchvision 0.7.0
