### ISSUE TITLE
How to using Ens

### ISSUE THREAD

**Issue by zhengshangdong** [ppengtang/pcl.pytorch#58]
Thanks so much for your great job！
I have ran your code and mAP is about 50.05%~50.90%  in my experiments.
I suppose the 54.1%mAP in your experiments can be gained by Ens.?
So, how to realize the Ens. operation or have the Ens. operation contained in your code(where).

 Looking forward to your reply！

**Comment by HMCCMH** [comment]
I want to know it, too.

**Comment by ppengtang** [comment]
Hi, sorry for the late reply. The 54.1%mAP is obtained by a single VGG16 based model (no Ens.) using [vgg16_voc2007_more.yaml](https://github.com/ppengtang/pcl.pytorch/blob/master/configs/baselines/vgg16_voc2007_more.yaml). 
It seems that vgg16_voc2007_more.yaml is not very stable and you could try vgg16_voc2007.yaml to get more stable results. Or you could use my trained models [here](https://drive.google.com/drive/folders/1OG56zqBv_gbLsDXySpLi55bYy5Q9Tf2-?usp=sharing).

I did ensemble for caffe version models only and haven't tried it for PyTorch version models. To do ensemble, I trained a VGG_M based PCL model and a VGG16 based PCL model, and computed the average score from these two models for each proposal.

**Comment by hpu-dxx** [comment]
> Thanks so much for your great job！ I have ran your code and mAP is about 50.05%~50.90% in my experiments. I suppose the 54.1%mAP in your experiments can be gained by Ens.? So, how to realize the Ens. operation or have the Ens. operation contained in your code(where).
> 
> Looking forward to your reply！

hello,Have you implemented Ens?
