### ISSUE TITLE
Differences between Papers and Codes

### ISSUE THREAD

**Issue by zwyyy215** [ppengtang/pcl.pytorch#6]
When finding proposal cluster centers，the end condition of the cycle written in the paper is that the vertex Vk is empty in the graph.
But in code, the condition for the loop to end is count <= 5.
I don't understand a bit.

**Comment by ppengtang** [comment]
Hi, thanks for your question.
Please refer to Section 4.2.9 in the paper for more details.

**Comment by zwyyy215** [comment]
Thank you！
