### ISSUE TITLE
Question about +FRCNN

### ISSUE THREAD

**Issue by hhhh12345678** [ppengtang/pcl.pytorch#62]
Thanks for your great job~

I have a question that with nothing about this article. I am sorry about put this on issues, but I do not get suitable one to discuss with. Hope you can understand and give your advices.

Q: Based on your codes, I got 53.1mAP on VOC2007. Then I used the WSOD results to trian the fully supervised object detector (FSOD) with Faster-RCNN and FPN. But **I got a very low performance on VOC2007(41.3mAP)** whice is very confusing. From the articles I read before (such as OICR, WSDDN, PCL), althought based on Faster-RCNN instead of Fast-rcnn, training a FSOD based on WSOD results can always gets a better mAP than using single WSOD. Is this caused by the different of Faster-RCNN and Fast-RCNN? Based on your experience, do you have any other suggestions for this situation？

**Comment by ppengtang** [comment]
I haven't tried PCL + Faster R-CNN. For the PCL + Fast R-CNN experiments reported in my papers, here are some tricks to ensure high numbers:
1. setting batch size to 2048/4096 when training Fast R-CNN.
2. adding dilation to the final conv stage.
3. using multi-scale training and testing.

Hope these tricks could be helpful.

**Comment by hhhh12345678** [comment]
Thanks for your tricks!

How can I run the FRCNN by setting batch size to 2048/4096? it seems too big.

In normal case, when i setting the batch size larger than 8, the GPU would report CUDA MEMORY ERROR.

**Comment by HMCCMH** [comment]
> Thanks for your tricks!
> 
> How can I run the FRCNN by setting batch size to 2048/4096? it seems too big.
> 
> In normal case, when i setting the batch size larger than 8, the GPU would report CUDA MEMORY ERROR.

Hello, do you use the Pytorch OICR to retrain FRCNN? Can you tell me how can I use the results of Pytorch OICR to retrain FRCNN?
