### ISSUE TITLE
The problem about the validation of VOC2007

### ISSUE THREAD

**Issue by HMCCMH** [ppengtang/pcl.pytorch#63]
I see that the PCL of the python version doesn't have the function to verify the (VOC2007) mAP of the model with the MATLAB, it only has the python version to verify the mAP. However, you tell us  to use the officical MATLAB code for VOC2007 validation. So I want to know how to use the model to connect the MATLAB, thank you!!!!

**Comment by Glutton-zh** [comment]
Hello, I have the same question as you after using the code. Have you solved it and can you give me some suggestions?

**Comment by HMCCMH** [comment]
> Hello, I have the same question as you after using the code. Have you solved it and can you give me some suggestions?

You could download VOCdevkit_08-Jun-2007.tar and extract it. Then you put the python test results(comp4_*_det_*.txt) to  /VOCdevkit/results/VOC2007/Main/.
After that, you could  refer to example_detector.m for making matlab code.
