### ISSUE TITLE
How to get comp4_*_det_*.txt for VOC2012

### ISSUE THREAD

**Issue by HMCCMH** [ppengtang/pcl.pytorch#64]
Thank you for your good work!
But I wanna know how to get the results of comp4.txt for VOC2012. I use the test_net.py for testing VOC2012test，but the code has errors and only produces detections.pkl.

**Comment by ghZHM** [comment]
hello, I have the same problem, the error is caused by missing annotations of the test set. Could you please tell me how did you fix it

**Comment by Glutton-zh** [comment]
> hello, I have the same problem, the error is caused by missing annotations of the test set. Could you please tell me how did you fix it

Hello, have you solved this problem and how do you get the comp3_det_test_*.txt, Thanks

**Comment by ghZHM** [comment]
@Glutton-zh I am sorry, I did not solve it.
