### ISSUE TITLE
Implementation of RPN from "Weakly Supervised Region Proposal Network and Object Detection"

### ISSUE THREAD

**Issue by vadimkantorov** [ppengtang/pcl.pytorch#65]
By chance, does this repo also contain RPN impl from "Weakly Supervised Region Proposal Network
and Object Detection"? Thanks :)

**Comment by ppengtang** [comment]
I didn't add codes of weakly supervised RPN because I found that weakly supervised RPN doesn't obtain better results than Selective Search for the updated OICR/PCL. So I would suggest you use Selective Search for convenience.

**Comment by vadimkantorov** [comment]
This code would still be useful. I'm working on a project of self-supervised RPN pretraining, it would be a useful baseline! So if you still have it, even a code drop would be useful. Thanks :)

**Comment by ppengtang** [comment]
> 

@vadimkantorov Sorry I cannot find my codes. I only have MATLAB codes to generate coarse proposals based on responses of conv layers: https://drive.google.com/file/d/1Zjgc8A60gfmbeeCNUuBF1sH2A1ngIvZr/view?usp=sharing. It should be used together with the Edge Boxes codes (https://github.com/pdollar/edges). Hope this could be helpful.
