### ISSUE TITLE
I am a fresh of leaning PyTorch. When try to train the PCL, I got the fellow error and don’t know how to adress it. Thanks in advance.

### ISSUE THREAD

**Issue by theshy456** [ppengtang/pcl.pytorch#67]
![微信图片_20211113212907](https://user-images.githubusercontent.com/63041101/142822621-53d96f22-5604-48d5-b8ae-c2b60e7b4b29.png)

**Comment by dingjietao** [comment]
> ![微信图片_20211113212907](https://user-images.githubusercontent.com/63041101/142822621-53d96f22-5604-48d5-b8ae-c2b60e7b4b29.png)

I think you should check datasets path, or corresponding xml.

**Comment by theshy456** [comment]
> > ![微信图片_20211113212907](https://user-images.githubusercontent.com/63041101/142822621-53d96f22-5604-48d5-b8ae-c2b60e7b4b29.png)
> 
> I think you should check datasets path, or corresponding xml.

**Comment by theshy456** [comment]
Thank for your reply.It works.
