### ISSUE TITLE
an install error

### ISSUE THREAD

**Issue by fsted** [ppengtang/pcl.pytorch#68]
when i install the mmcv by:
pip --no-cache-dir install mmcv-full==latest+torch1.6.0+cu101 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html
in the install.sh
A strange error appeared：
pip._vendor.packaging.version.InvalidVersion: Invalid version: 'latest+torch1.6.0+cu101'
How should i do,Thanks :)

**Comment by ppengtang** [comment]
Could you try to follow the original mmcv installation guideline to install mmcv: https://github.com/open-mmlab/mmcv#installation ?
