### ISSUE TITLE
About result of vgg16_voc2007.xml 

### ISSUE THREAD

**Issue by theshy456** [ppengtang/pcl.pytorch#73]
Thanks for your nice code. I found the result of vgg16_voc2007.yaml is only 50.9 mAP in my experiment. Could you help me choose the correct $MODEL_PATH？

CUDA_VISIBLE_DEVICES=0 python tools/test_net.py --cfg configs/baselines/vgg16_voc2007.yaml \
  --load_ckpt Outputs/vgg16_voc2007/$MODEL_PATH \
  --dataset voc2007trainval

**Comment by ppengtang** [comment]
You can try this one: https://drive.google.com/file/d/1jKjA4fO_Drd6Coqnd4w9Cmv0aCkuO-Yj/view?usp=sharing

**Comment by theshy456** [comment]
Thanks for your reply.The best results usually are not achieved in the last epoch.Which intermediate model is the best？24999.pth or others？Which intermediate model corresponds the above link given by you ？Looking forward to your response.

**Comment by theshy456** [comment]
> You can try this one: https://drive.google.com/file/d/1jKjA4fO_Drd6Coqnd4w9Cmv0aCkuO-Yj/view?usp=sharing
Thanks for your reply.As the following picture shows,Which intermediate model corresponds the above link given by you?
![微信图片_20220115132605(复件)](https://user-images.githubusercontent.com/63041101/149610263-80acbe95-08c0-4955-b40e-5f09e1778eb9.png)

**Comment by theshy456** [comment]
> You can try this one: https://drive.google.com/file/d/1jKjA4fO_Drd6Coqnd4w9Cmv0aCkuO-Yj/view?usp=sharing

Thanks for your reply.The above link does achieve a map value of 52.9，But I can only get a map of 50.4-50.9 according to readme.md.Can you tell me how to get your  model?
