### ISSUE TITLE
How to generate some visualizations？

### ISSUE THREAD

**Issue by theshy456** [ppengtang/pcl.pytorch#74]

**Comment by hpu-dxx** [comment]
> _No description provided._

请问您怎么实现了可视化？

**Comment by hpu-dxx** [comment]
@theshy456 请问您怎么实现了可视化？

**Comment by theshy456** [comment]
> @theshy456 请问您怎么实现了可视化？

我还没实现，这有两个网址，你可以试一下。[https://www.1024sou.com/article/15859.html](url)
[https://www.1024sou.com/article/15859.html](url)

**Comment by hpu-dxx** [comment]
> 

谢谢。

**Comment by dingjietao** [comment]
> @theshy456 请问您怎么实现了可视化？

请问您实现可视化了吗
