### ISSUE TITLE
The problem with testing coco datasets

### ISSUE THREAD

**Issue by HMCCMH** [ppengtang/pcl.pytorch#77]
When the code finishing the test, the program was killed. And the detection.pkl was 0 Kb and there is no results.

`INFO test_engine.py: 281: im_detect: range [1, 40504] of 40504: 40471/40504 1.306s (eta: 0:00:43)` 
`INFO test_engine.py: 281: im_detect: range [1, 40504] of 40504: 40481/40504 1.306s (eta: 0:00:30)`
`INFO test_engine.py: 281: im_detect: range [1, 40504] of 40504: 40491/40504 1.306s (eta: 0:00:16)`
`INFO test_engine.py: 281: im_detect: range [1, 40504] of 40504: 40501/40504 1.306s (eta: 0:00:03)`
`Killed`

**Comment by bityangke** [comment]
OOM？

**Comment by HMCCMH** [comment]
> OOM？

I used the 2080Ti GPU. It wasn't OOM.

**Comment by HMCCMH** [comment]
> OOM？

I  tested it agin and used `dmesg | egrep -i -B100 'killed process'`. And I found that it was OOM.

```
[12686762.082512] Out of memory: Kill process 135509 (python3.6) score 894 or sacrifice child
[12686762.082887] Killed process 135509 (python3.6) total-vm:324591472kB, anon-rss:233040056kB, file-rss:85428kB
```

So the detections.pkl can't be saved.
